pipeline {
    agent any

    stages {

        stage('Show Files') {
            steps {
                echo "Listing files in workspace"
                bat 'dir'
            }
        }

        stage('Build') {
            steps {
                echo "Building the project"
                bat 'mvn clean compile'
            }
        }

        stage('Automated Testing') {
            steps {
                echo "Running automated tests"
                bat 'mvn test'
            }
        }

        stage('Test Report') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }

    }
}
