pipeline {
    agent any

    stages {

       stage('Show Files') {
    steps {
        bat 'dir'
    }
}

        stage('Build') {
            steps {
                echo 'Build Successful'
            }
        }

    }
}
